spring.application.name=webGame
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.password=root
spring.datasource.username=postgres
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
